name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.5.0'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build   # Replace 'build' with your build command

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Checkout the gh-pages branch
          git checkout gh-pages

          # Remove old files
          git rm -rf .

          # Copy generated static files
          cp -r /public

          # Commit and push changes
          git add .
          git commit -m "Deploy static files to GitHub Pages"
          git push origin main
