name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install openssh-client

      - name: Set up known hosts
        run: ssh-keyscan 13.40.194.77 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@13.40.194.77 'cd /var/www/html && git pull origin main'
